# Generated by Django 4.2.1 on 2023-05-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='code',
            field=models.CharField(default='AAA111', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.PositiveIntegerField(choices=[(1, 'Waiting'), (2, 'Starting'), (3, 'Initiated'), (4, 'Ended')]),
        ),
    ]
