# Generated by Django 4.2.1 on 2023-05-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_game_alter_customuser_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='arrival_city',
            field=models.CharField(default='PARIS', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='departure_city',
            field=models.CharField(default='BARCELONA', max_length=30),
            preserve_default=False,
        ),
    ]
