WAITING = 1
STARTING = 2
INITIATED = 3
ENDED = 4
MAX_USERS = 5

#RESPONSE CODES
ROOM_FOUND_CODE = 1
ROOM_NOT_FOUND_CODE = 2
ROOM_BUSY_CODE = 3
JOIN_WAITING_ROOM_CODE = 4
JOIN_STARTING_ROOM_CODE = 5
ROOM_CREATED = 6

DEPARTURE_CITY = "BARCELONA"
ARRIVAL_CITY = "PARIS"


STATE = [
    (WAITING, 'Waiting'),
    (STARTING, 'Starting'),
    (INITIATED, 'Initiated'),
    (ENDED, 'Ended')
]