WAITING = 1
UPLOADING_IMAGES = 2
INITIATED = 3
ENDED = 4
MAX_USERS = 5

#RESPONSE CODES
ROOM_FOUND_CODE = 1
ROOM_NOT_FOUND_CODE = 2
ROOM_BUSY_CODE = 3
JOIN_WAITING_ROOM_CODE = 4
JOIN_STARTING_ROOM_CODE = 5
ROOM_CREATED = 6
NOT_AN_ADMIN = 7
NOT_IN_A_GAME = 8
GAME_HAS_ALREADY_STARTED = 9
NEED_MORE_PLAYERS = 10
UPLOAD_IMAGES = 11
NEED_MORE_IMAGES = 12

DEPARTURE_CITY = "BARCELONA"
ARRIVAL_CITY = "PARIS"


STATE = [
    (WAITING, 'Waiting'),
    (UPLOADING_IMAGES, 'Starting'),
    (INITIATED, 'Initiated'),
    (ENDED, 'Ended')
]